OnlinePizzeria/Controllers/CustomPizzaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class CustomPizzaController : Controller
    {
        private readonly CustomPizzaService customPizzaService;

        public CustomPizzaController(CustomPizzaService service)
        {
            customPizzaService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<CustomPizzaViewModel> pizzas = customPizzaService.GetAll();
            return View(pizzas);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            CustomPizzaViewModel pizza = customPizzaService.GetDetailsById(id);
            bool isPizzaNull = pizza == null;
            if (isPizzaNull)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpGet]
        public IActionResult AddCustomPizza()
        {
            ViewBag.Orders = customPizzaService.GetOrders();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCustomPizza(CustomPizzaViewModel pizza)
        {
            if (pizza == null)
            {
                return BadRequest("Invalid custom pizza data");
            }
            
            float price = customPizzaService.CalculatePizza(pizza);
            pizza.Price = price;
            await customPizzaService.CreateAsync(pizza);
            TempData["success"] = "Custom pizza added successfully";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult DeleteCustomPizza()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCustomPizza(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await customPizzaService.DeleteCustomPizza(id);
            TempData["success"] = "Custom pizza deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCustomPizza(string id)
        {
            ViewBag.Orders = customPizzaService.GetOrders();
            CustomPizzaViewModel pizza = await customPizzaService.UpdateById(id);

            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCustomPizza(CustomPizzaViewModel model)
        {
            bool customPizzaExists = await CustomPizzaExists(model.Id!);

            if (customPizzaExists)
            {
                float price = customPizzaService.CalculatePizza(model);
                model.Price = price;
                await customPizzaService.UpdateAsync(model);
                TempData["success"] = "Custom pizza updated successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Custom pizza not found");
            }

            return View(model);
        }

        private async Task<bool> CustomPizzaExists(string id)
        {
            return await customPizzaService.CustomPizzaExists(id);
        }
    }
}

OnlinePizzeria/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlinePizzeria.Model;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class OrderController : Controller
    {
        public OrderService orderService { get; set; }

        public OrderController(OrderService service)
        {
            orderService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<OrderViewModel> orders = orderService.GetAll();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            OrderViewModel order = orderService.GetDetailsById(id);
            bool isCourseNull = order == null;
            if (isCourseNull)
            {
                return NotFound();
            }

            return this.View(order);
        }
        [HttpGet]
        public IActionResult AddOrder()
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrder(OrderViewModel order)
        {
            if (order == null)
            {
                return BadRequest("Invalid order data");
            }

            TempData["success"] = "Order added successfully";
            await orderService.CreateAsync(order);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult DeleteOrder()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrder(string id)
        {
            OrderViewModel order = orderService.GetDetailsById(id);
            if (order == null)
            {
                return NotFound();
            }
            TempData["success"] = "Order deleted successfully";
            await orderService.DeleteOrder(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateOrder(string id)
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            OrderViewModel order = await orderService.UpdateById(id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdateOrder(OrderViewModel model)
        {
            bool orderExists = await OrderExists(model.Id!);

            if (orderExists)
            {
               TempData["success"] = "Order updated successfully";
               await orderService.UpdateAsync(model);
               return RedirectToAction(nameof(Index));
            }

            else
            {
               ModelState.AddModelError(string.Empty, "Order not found");
            }

            return View(model);
        }
        
        private async Task<bool> OrderExists(string id)
        {
            return await orderService.OrderExists(id);
        }
    }
}

OnlinePizzeria/Controllers/PizzaModelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using OnlinePizzeria.Data;
using OnlinePizzeria.Model;
using OnlinePizzeria.Models;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class PizzaModelController : Controller
    {
        private readonly PizzaModelService pizzaService;

        public PizzaModelController(PizzaModelService service)
        {
            pizzaService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<PizzaViewModel> pizzas = pizzaService.GetAll();
            return View(pizzas);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ViewBag.Orders = pizzaService.GetOrders();
            PizzaViewModel pizza = pizzaService.GetDetailsById(id);
            bool isPizzaNull = pizza == null;
            if (isPizzaNull)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpGet]
        public IActionResult AddPizza()
        {
            ViewBag.Orders = pizzaService.GetOrders();
            return View();
        }

         [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPizza(PizzaViewModel pizza, IFormFile imageFile)
        {
            if (pizza == null)
            {
                return BadRequest("Invalid pizza data");
            }

            float price = pizzaService.CalculatePizza(pizza);
            pizza.Price = price;

            if (imageFile != null && imageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await imageFile.CopyToAsync(memoryStream);
                    pizza.ImageData = memoryStream.ToArray();
                }

                ViewBag.Orders = pizzaService.GetOrders();
                await pizzaService.CreateAsync(pizza, imageFile);
                TempData["success"] = "Pizza added successfully";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                ModelState.AddModelError(string.Empty, "No image file provided");
            }

            return View(pizza);
        }

        [HttpGet]
        public IActionResult DeletePizza()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePizza(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await pizzaService.DeletePizza(id);
            TempData["success"] = "Pizza deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePizza(string id)
        {
            ViewBag.Orders = pizzaService.GetOrders();
            if (id == null)
            {
                return NotFound();
            }

            PizzaViewModel pizza = await pizzaService.UpdateById(id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePizza(PizzaViewModel model, IFormFile imageFile)
        {
            float price = pizzaService.CalculatePizza(model);
            model.Price = price;

            if (imageFile != null && imageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await imageFile.CopyToAsync(memoryStream);
                    model.ImageData = memoryStream.ToArray();
                }
                await pizzaService.UpdateAsync(model, imageFile);
                TempData["success"] = "Pizza updated successfully";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                ModelState.AddModelError(string.Empty, "No image file provided");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult PizzaDetails(string id, string imageUrl)
        {
            var pizza = pizzaService.GetDetailsById(id);

            if (pizza == null)
            {
                return NotFound();
            }

            pizza.ImageUrl = imageUrl;

            return View(pizza);
        }
    }
}

OnlinePizzeria/Views/PizzaModel/CustomPizzaIndex.cshtml
@model PizzaViewModel
@using OnlinePizzeria.Data.DataModels;
@{
}
<!DOCTYPE html>
<html>
   <head>
      <title>Custom Pizza</title>
   </head>
   <body>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h1 class="text-center mb-4">Create your own Pizza</h1>
                                <form method="post">
                                    <div class="form-group">
                                        <label asp-for="PizzaName">Pizza Name:</label>
                                        <input asp-for="PizzaName" class="form-control" placeholder="Give your pizza a name...">
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="PizzaSize.Size">Size:</label>
                                        <select asp-for="PizzaSize.Size" class="form-control">
                                            <option value="@PizzaSize.SizeType.Small">Small</option>
                                            <option value="@PizzaSize.SizeType.Medium">Medium</option>
                                            <option value="@PizzaSize.SizeType.Large">Large</option>
                                        </select>
                                    </div>
                                    <h2>Toppings:</h2>
                                    <div class="form-group form-check">
                                        <input asp-for="TomatoSauce" type="checkbox" class="form-check-input">
                                        <label asp-for="TomatoSauce" class="form-check-label">Tomato Sauce</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Cheese" type="checkbox" class="form-check-input">
                                        <label asp-for="Cheese" class="form-check-label">Cheese</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Peperoni" type="checkbox" class="form-check-input">
                                        <label asp-for="Peperoni" class="form-check-label">Pepperoni</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Ham" type="checkbox" class="form-check-input">
                                        <label asp-for="Ham" class="form-check-label">Ham</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Mushroom" type="checkbox" class="form-check-input">
                                        <label asp-for="Mushroom" class="form-check-label">Mushroom</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Tuna" type="checkbox" class="form-check-input">
                                        <label asp-for="Tuna" class="form-check-label">Tuna</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Beef" type="checkbox" class="form-check-input">
                                        <label asp-for="Beef" class="form-check-label">Beef</label>
                                    </div>
                                    <div class="form-group form-check">
                                        <input asp-for="Pineapple" type="checkbox" class="form-check-input">
                                        <label asp-for="Pineapple" class="form-check-label">Pineapple</label>
                                    </div>
                                    <h2>Ingredient Weights:</h2>
                                    <div class="form-group">
                                    <label asp-for="ProductWeight.TomatoWeight">Tomato Weight:</label>
                                    <select asp-for="ProductWeight.TomatoWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.CheeseWeight">Cheese Weight:</label>
                                    <select asp-for="ProductWeight.CheeseWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.PeperoniWeight">Peperoni Weight:</label>
                                    <select asp-for="ProductWeight.PeperoniWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.MushroomWeight">Mushroom Weight:</label>
                                    <select asp-for="ProductWeight.MushroomWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.TunaWeight">Tuna Weight:</label>
                                    <select asp-for="ProductWeight.TunaWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.PineappleWeight">Pineapple Weight:</label>
                                    <select asp-for="ProductWeight.PineappleWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.HamWeight">Ham Weight:</label>
                                    <select asp-for="ProductWeight.HamWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                    <label asp-for="ProductWeight.BeefWeight">Beef Weight:</label>
                                    <select asp-for="ProductWeight.BeefWeight" class="form-control">
                                        <option value="@WeightOption.Choice.None">None</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Light</option>
                                        <option value="@WeightOption.Choice.Light">Light</option>
                                        <option value="@WeightOption.Choice.Normal">Normal</option>
                                        <option value="@WeightOption.Choice.Heavy">Heavy</option>
                                        <option value="@WeightOption.Choice.ExtraHeavy">Extra Heavy</option>
                                    </select>
                                </div>
                                <button class="btn btn-primary mt-3" type="submit" asp-controller="PizzaModel" asp-action="CreditCardIndex">Order my pizza</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </body>
</html>

OnlinePizzeria/Views/PizzaModel/Index.cshtml
@model List<PizzaViewModel>
@{
	ViewData["Title"] = "List of Pizzas";

}

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-primary text-white ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Pizza List</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-controller="PizzaModel" asp-action="AddPizza" class="btn btn-outline-primary">
					<i class="bi bi-plus-circle"></i>Create New Pizza
				</a>
			</div>
		</div>
		<table class="table table-bordered table-striped">
			<thead>
				<tr class="text-center">
					<th>Pizza name</th>
					<th>Tomato sauce</th>
					<th>Cheese</th>
					<th>Pepperoni</th>
					<th>Mushroom</th>
					<th>Tuna</th>
					<th>Pineapple</th>
					<th>Ham</th>
					<th>Beef</th>
					<th>Price</th>
					<th>Image</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var pizza in Model)
				{
					<tr class="text-center">
						<td>@Html.DisplayFor(model => pizza.PizzaName)</td>
						<td>@Html.DisplayFor(model => pizza.TomatoSauce)</td>
						<td>@Html.DisplayFor(model => pizza.Cheese)</td>
						<td>@Html.DisplayFor(model => pizza.Peperoni)</td>
						<td>@Html.DisplayFor(model => pizza.Mushroom)</td>
						<td>@Html.DisplayFor(model => pizza.Tuna)</td>
						<td>@Html.DisplayFor(model => pizza.Pineapple)</td>
						<td>@Html.DisplayFor(model => pizza.Ham)</td>
						<td>@Html.DisplayFor(model => pizza.Beef)</td>
						<td>
							<span class="currency-symbol">лв.</span>
							@Html.DisplayFor(model => pizza.Price)
						</td>

						<td class="text-center">
							@if (!string.IsNullOrEmpty(pizza.ImageUrl))
							{
								<img src="@Url.Content(pizza.ImageUrl)" alt="Pizza Image" width="150" height="150" />
							}
						</td>
						<td>
							<div class="w-100 btn-group" role="group">
								<a class="btn btn-outline-primary" asp-action="UpdatePizza" asp-route-id="@pizza.Id"><i class="bi bi-pencil square">Update</i></a>
								<a class="btn btn-outline-info" asp-action="Details" asp-route-id="@pizza.Id"><i class="bi bi-eye"></i>Details</a>
								<a class="btn btn-outline-danger" asp-action="DeletePizza" asp-route-id="@pizza.Id"><i class="bi bi-trash"></i>Delete</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>
<div class="row mt-4 justify-content-center">
	<div class="col-lg-4 col-md-6">
		<div class="card text-center">
			<img src="~/images/Create.png" alt="Create Pizza" class="card-img-top img-fluid">
			<div class="card-body">
				<h4 class="card-title">Create Your Own Pizza</h4>
				<p class="card-text">Create your custom pizza with your favorite toppings.</p>
				<a href="@Url.Action("AddCustomPizza", "CustomPizza")" class="btn btn-outline-primary btn-lg">Customize Now</a>
			</div>
		</div>
	</div>
</div>
<div class="row mt-4">
	@foreach (var pizza in Model)
	{
		<div class="col-md-4 mb-4">
			<div class="card">
				<img src="@Url.Content(pizza.ImageUrl)" alt="Pizza Image" class="card-img-top img-thumbnail" width="50" height="50">
				<div class="card-body d-flex flex-column">
					<a href="@Url.Action("PizzaDetails", new { id = pizza.Id, imageUrl = pizza.ImageUrl })" class="btn btn-outline-info">Read More</a>
				</div>
			</div>
		</div>
	}
</div>
<style>
	.currency-symbol {
		font-weight: bold;
		color: lightgreen;
		margin-left: 2px;
		float: right;
	}
</style>

OnlinePizzeria/Views/PizzaModel/PizzaDetails.cshtml
@using System.Globalization;
@model PizzaViewModel

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-img-container text-center">
                    <img src="@Model.ImageUrl" alt="Pizza Image" class="card-img-top img-fluid" style="width: 50%;" />
                </div>
                <div class="card-body text-center">
                    <h2 class="card-title">@Model.PizzaName</h2>
                    <p class="card-text">Description: @Model.Description</p>
                    <p class="card-text">Price: @Model.Price.ToString("C", CultureInfo.GetCultureInfo("bg-BG"))</p>
                    <div class="d-flex justify-content-start">
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                    <div class="d-flex justify-content-end">
                        <a asp-controller="Order" asp-action="AddOrder" asp-route-price="@Model.Price" class="btn btn-outline-primary justify-content-sm-end">Order Now!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>