OnlinePizzeria/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlinePizzeria.Model;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class CustomerController : Controller
    {
        public CustomerService customerService { get; set; }
        public CustomerController(CustomerService service)
        {
            customerService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<CustomerViewModel> customers = customerService.GetAll();
            return View(customers);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            CustomerViewModel customer = customerService.GetDetailsById(id);
            bool isCourseNull = customer == null;
            if (isCourseNull)
            {
                return NotFound();
            }

            return this.View(customer);
        }
        [HttpGet]
        public IActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCustomer(CustomerViewModel customer)
        {
            if (customer == null)
            {
                return BadRequest("Invalid customer data");
            }

            TempData["success"] = "Customer added successfully";
            await customerService.CreateAsync(customer);
            return RedirectToAction(nameof(Index));
        }
        
        [HttpGet]
        public IActionResult DeleteCustomer()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCustomer(string id)
        {
            CustomerViewModel customer = customerService.GetDetailsById(id);
            if (customer == null)
            {
                return NotFound();
            }
            TempData["success"] = "Customer deleted successfully";
            await customerService.DeleteCustomer(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCustomer(string id)
        {
            CustomerViewModel customer = await customerService.UpdateById(id);

            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdateCustomer(CustomerViewModel model)
        {
            bool customerExists = await CustomerExists(model.Id!);

            if (customerExists)
            {
                TempData["success"] = "Customer updated successfully";
                await customerService.UpdateAsync(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Customer not found");
            }

            return View(model);
        }
        
        private async Task<bool> CustomerExists(string id)
        {
            return await customerService.CustomerExists(id);
        }
    }
}

OnlinePizzeria/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlinePizzeria.Model;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class OrderController : Controller
    {
        public OrderService orderService { get; set; }

        public OrderController(OrderService service)
        {
            orderService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<OrderViewModel> orders = orderService.GetAll();
            return View(orders);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            OrderViewModel order = orderService.GetDetailsById(id);
            bool isCourseNull = order == null;
            if (isCourseNull)
            {
                return NotFound();
            }

            return this.View(order);
        }
        [HttpGet]
        public IActionResult AddOrder()
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrder(OrderViewModel order)
        {
            if (order == null)
            {
                return BadRequest("Invalid order data");
            }

            TempData["success"] = "Order added successfully";
            await orderService.CreateAsync(order);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult DeleteOrder()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrder(string id)
        {
            OrderViewModel order = orderService.GetDetailsById(id);
            if (order == null)
            {
                return NotFound();
            }
            TempData["success"] = "Order deleted successfully";
            await orderService.DeleteOrder(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateOrder(string id)
        {
            ViewBag.Customers = orderService.GetCustomers();
            ViewBag.Providers = orderService.GetProviders();
            OrderViewModel order = await orderService.UpdateById(id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdateOrder(OrderViewModel model)
        {
            bool orderExists = await OrderExists(model.Id!);

            if (orderExists)
            {
               TempData["success"] = "Order updated successfully";
               await orderService.UpdateAsync(model);
               return RedirectToAction(nameof(Index));
            }

            else
            {
               ModelState.AddModelError(string.Empty, "Order not found");
            }

            return View(model);
        }
        
        private async Task<bool> OrderExists(string id)
        {
            return await orderService.OrderExists(id);
        }
    }
}

OnlinePizzeria/Controllers/PizzaModelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using OnlinePizzeria.Data;
using OnlinePizzeria.Model;
using OnlinePizzeria.Models;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
    public class PizzaModelController : Controller
    {
        private readonly PizzaModelService pizzaService;

        public PizzaModelController(PizzaModelService service)
        {
            pizzaService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<PizzaViewModel> pizzas = pizzaService.GetAll();
            return View(pizzas);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ViewBag.Orders = pizzaService.GetOrders();
            PizzaViewModel pizza = pizzaService.GetDetailsById(id);
            bool isPizzaNull = pizza == null;
            if (isPizzaNull)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpGet]
        public IActionResult AddPizza()
        {
            ViewBag.Orders = pizzaService.GetOrders();
            return View();
        }

         [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPizza(PizzaViewModel pizza, IFormFile imageFile)
        {
            if (pizza == null)
            {
                return BadRequest("Invalid pizza data");
            }

            float price = pizzaService.CalculatePizza(pizza);
            pizza.Price = price;

            if (imageFile != null && imageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await imageFile.CopyToAsync(memoryStream);
                    pizza.ImageData = memoryStream.ToArray();
                }

                ViewBag.Orders = pizzaService.GetOrders();
                await pizzaService.CreateAsync(pizza, imageFile);
                TempData["success"] = "Pizza added successfully";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                ModelState.AddModelError(string.Empty, "No image file provided");
            }

            return View(pizza);
        }

        [HttpGet]
        public IActionResult DeletePizza()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePizza(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await pizzaService.DeletePizza(id);
            TempData["success"] = "Pizza deleted successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePizza(string id)
        {
            ViewBag.Orders = pizzaService.GetOrders();
            if (id == null)
            {
                return NotFound();
            }

            PizzaViewModel pizza = await pizzaService.UpdateById(id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePizza(PizzaViewModel model, IFormFile imageFile)
        {
            float price = pizzaService.CalculatePizza(model);
            model.Price = price;

            if (imageFile != null && imageFile.Length > 0)
            {
                using (var memoryStream = new MemoryStream())
                {
                    await imageFile.CopyToAsync(memoryStream);
                    model.ImageData = memoryStream.ToArray();
                }
                await pizzaService.UpdateAsync(model, imageFile);
                TempData["success"] = "Pizza updated successfully";
                return RedirectToAction(nameof(Index));
            }

            else
            {
                ModelState.AddModelError(string.Empty, "No image file provided");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult PizzaDetails(string id, string imageUrl)
        {
            var pizza = pizzaService.GetDetailsById(id);

            if (pizza == null)
            {
                return NotFound();
            }

            pizza.ImageUrl = imageUrl;

            return View(pizza);
        }
    }
}

OnlinePizzeria/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
	public class ProviderController : Controller
	{
        public ProviderService providerService { get; set; }

        public ProviderController(ProviderService service)
        {
            providerService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<ProviderViewModel> providers = providerService.GetAll();
            return View(providers);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ProviderViewModel provider = providerService.GetDetailsById(id);
            bool isCourseNull = provider == null;
            if (isCourseNull)
            {
                return NotFound();
            }

            return this.View(provider);
        }
        [HttpGet]
        public IActionResult AddProvider()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProvider(ProviderViewModel provider)
        {
            if (provider == null)
            {
                return BadRequest("Invalid provider data");
            }

            TempData["success"] = "Provider added successfully";
            await providerService.CreateAsync(provider);
            return RedirectToAction(nameof(Index));
        }
	
        [HttpGet]
        public IActionResult DeleteProvider()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteProvider(string id)
        {
            ProviderViewModel provider = providerService.GetDetailsById(id);
            if (provider == null)
            {
                return NotFound();
            }
            TempData["success"] = "Provider deleted successfully";
            await providerService.DeleteProvider(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProvider(string id)
        {
            ProviderViewModel provider = await providerService.UpdateById(id);

            if (provider == null)
            {
                return NotFound();
            }
            return View(provider);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdateProvider(ProviderViewModel model)
        {
            bool providerExists = await ProviderExists(model.Id!);

            if (providerExists)
            {
                TempData["success"] = "Provider updated successfully";
                await providerService.UpdateAsync(model);
                return RedirectToAction(nameof(Index));
            }

            else
            {
                ModelState.AddModelError(string.Empty, "Provider not found");
            }

            return View(model);
        }
	
        private async Task<bool> ProviderExists(string id)
        {
            return await providerService.ProviderExists(id);
        }
    }
}

OnlinePizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlinePizzeria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlinePizzeria.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"/>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlinePizzeria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }
                        @if(ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PizzaModel" asp-action="Index">Pizzas</a>
                            </li>
                        }
                        @if(ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="CustomPizza" asp-action="Index">Custom Pizza</a>
                            </li>
                        }
                        @if(ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Order" asp-action="Index">Orders</a>
                            </li>
                        }
                        @if(ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="CreditCardPayment" asp-action="Index">Payments</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Provider" asp-action="Index">Providers</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted fixed-bottom">
        <div class="text-center">
            &copy; 2023 - OnlinePizzeria - Made by Nikolai Mashkov 
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnlinePizzeria/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]')
    </script>
}