OnlinePizzeria/Controllers/CreditCardPaymentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlinePizzeria.Services;
using OnlinePizzeria.Services.Interfaces;
using OnlinePizzeria.Services.ViewModels;

namespace OnlinePizzeria.Controllers
{
	public class CreditCardPaymentController : Controller
	{
        public CreditCardPaymentService paymentService { get; set; }
        public CreditCardPaymentController(CreditCardPaymentService service)
        {
            paymentService = service;
        }
        [Authorize(Roles = "User")]
        [HttpGet]
        public IActionResult Index()
        {
            List<CreditCardPaymentViewModel> payments = paymentService.GetAll();
            return View(payments);
        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            ViewBag.Customers = paymentService.GetCustomers();
            ViewBag.Orders = paymentService.GetOrders();
            CreditCardPaymentViewModel payments = paymentService.GetDetailsById(id);
            bool isCourseNull = payments == null;
            if (isCourseNull)
            {
                return NotFound();
            }

            return this.View(payments);
        }
        [HttpGet]
        public IActionResult AddPayment()
        {
            ViewBag.Customers = paymentService.GetCustomers();
            ViewBag.Orders = paymentService.GetOrders();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPayment(CreditCardPaymentViewModel payment)
        {
            if(payment == null)
            {
                return BadRequest("Invalid payment data");
            }

            TempData["success"] = "Payment added successfully";
            await paymentService.CreateAsync(payment);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult DeletePayment()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePayment(string id)
        {
            CreditCardPaymentViewModel payment = paymentService.GetDetailsById(id);
            if (payment == null)
            {
                return NotFound();
            }
            TempData["success"] = "Payment deleted successfully";
            await paymentService.DeletePayment(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePayment(string id)
        {
            ViewBag.Customers = paymentService.GetCustomers();
            ViewBag.Orders = paymentService.GetOrders();
            CreditCardPaymentViewModel payment = await paymentService.UpdateById(id);

            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> UpdatePayment(CreditCardPaymentViewModel model)
        {
            bool paymentExists = await PaymentExists(model.Id!);

            if (paymentExists)
            {
                TempData["success"] = "Payment updated successfully";
                await paymentService.UpdateAsync(model);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Payment not found");
            }

            return View(model);
        }
	
        private async Task<bool> PaymentExists(string id)
        {
            return await paymentService.PaymentExists(id);
        }
    }
}

OnlinePizzeria/Views/CreditCardPayment/AddPayment.cshtml
@model CreditCardPaymentViewModel
@{
    ViewData["Title"] = "Add a new payment";
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Add Payment</h2>
                </div>
                <div class="card-body">
                    <form asp-action="AddPayment">
                        <div class="mb-3">
                            <label asp-for="CardNumber" class="form-label">Card Number:</label>
                            <input asp-for="CardNumber" class="form-control" pattern="^(?:(?<visa>4[0-9]{3}-?[0-9]{4}-?[0-9]{4}-?[0-9]{4}(?:-?[0-9]{3})?)|(?<mastercard>5[1-5][0-9]{14}))$" required placeholder="Enter a credit card number...">
                            <span asp-validation-for="CardNumber" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="CVV" class="form-label">CVV:</label>
                            <input asp-for="CVV" class="form-control" pattern="^[0-9]{3,4}$" required placeholder="Enter a valid CVV number...">
                            <span asp-validation-for="CVV" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="ExpirationDate" class="form-label">Expiration Date:</label>
                            <input asp-for="ExpirationDate" class="form-control" pattern="^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$" required placeholder="Enter a valid expiration date...">
                            <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Amount" class="form-label">Amount:</label>
                            <input asp-for="Amount" class="form-control" required placeholder="Enter an amount...">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="CustomerId" class="form-label">Customer:</label>
                            <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.Customers"></select>
                        </div>

                        <div class="mb-3">
                            <label asp-for="OrderId" class="form-label">Address:</label>
                            <select asp-for="OrderId" class="form-control" asp-items="ViewBag.Orders"></select>
                        </div>

                        <div class="mb-3">
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <input type="submit" value="Add" class="btn btn-outline-success">
                                <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

OnlinePizzeria/Views/CreditCardPayment/DeletePayment.cshtml
@model CreditCardPaymentViewModel
@{
    ViewData["Title"] = "Delete payment";
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Delete Payment</h2>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label asp-for="CardNumber" class="form-label">Card Number:</label>
                        <input asp-for="CardNumber" class="form-control" readonly>
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="CVV" class="form-label">CVV:</label>
                        <input asp-for="CVV" class="form-control" readonly>
                        <span asp-validation-for="CVV" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="ExpirationDate" class="form-label">Expiration Date:</label>
                        <input asp-for="ExpirationDate" class="form-control" readonly>
                        <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Amount" class="form-label">Amount:</label>
                        <input asp-for="Amount" class="form-control" readonly>
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="CustomerId" class="form-label">Customer:</label>
                        <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.Customers" disabled></select>
                    </div>

                    <div class="mb-3">
                        <label asp-for="OrderId" class="form-label">Address:</label>
                        <select asp-for="OrderId" class="form-control" asp-items="ViewBag.Orders" disabled></select>
                    </div>

                    <div class="mb-3">
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <form asp-action="DeletePayment">
                                <input type="submit" value="Confirm" onclick="return confirm('Are you sure you want to delete this payment?')" class="btn btn-outline-danger float-end" />
                            </form>
                            <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

OnlinePizzeria/Views/CreditCardPayment/Details.cshtml
@model CreditCardPaymentViewModel
@{
    ViewData["Title"] = "Details for payment";
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Details</h2>
                </div>
                <div class="card-body">
                    <div class="mb-3">
                        <label asp-for="CardNumber" class="form-label">Card Number:</label>
                        <input asp-for="CardNumber" class="form-control" pattern="^(?:(?<visa>4[0-9]{3}-?[0-9]{4}-?[0-9]{4}-?[0-9]{4}(?:-?[0-9]{3})?)|(?<mastercard>5[1-5][0-9]{14}))$" readonly>
                        <span asp-validation-for="CardNumber" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="CVV" class="form-label">CVV:</label>
                        <input asp-for="CVV" class="form-control" pattern="^[0-9]{3,4}$" readonly>
                        <span asp-validation-for="CVV" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="ExpirationDate" class="form-label">Expiration Date:</label>
                        <input asp-for="ExpirationDate" class="form-control" pattern="^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$" readonly>
                        <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Amount" class="form-label">Amount:</label>
                        <input asp-for="Amount" class="form-control" readonly>
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="CustomerId" class="form-label">Customer:</label>
                        @{
                            string customerFullName = $"{Model.Customer.FirstName} {Model.Customer.LastName}";
                        }
                        <input type="text" class="form-control" readonly value="@customerFullName">
                        <span asp-validation-for="CustomerId" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <label asp-for="Order.Address" class="form-label">Address:</label>
                        <input asp-for="Order.Address" class="form-control" readonly>
                        <span asp-validation-for="Order.Address" class="text-danger"></span>
                    </div>

                    <div class="mb-3">
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            <a class="btn btn-outline-success float-end" asp-action="UpdatePayment" asp-route-id="@Model.Id">Update</a>
                            <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

OnlinePizzeria/Views/CreditCardPayment/Index.cshtml
@model List<CreditCardPaymentViewModel>
@{
	ViewData["Title"] = "List of Payments";
}

<div class="card shadow border-0 mt-4">
	<div class="card-header bg-primary text-white ml-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h2 class="text-white py-2">Payment List</h2>
			</div>
		</div>
	</div>
	<div class="card-body p-4">
		<div class="row pb-3">
			<div class="col-6">
			</div>
			<div class="col-6 text-end">
				<a asp-controller="CreditCardPayment" asp-action="AddPayment" class="btn btn-outline-primary">
					<i class="bi bi-plus-circle"></i>Create New Payment
				</a>
			</div>
		</div>
		<table class="table table-bordered table-striped">
			<thead>
				<tr class="text-center">
					<th>Card Number</th>
					<th>Expiration Date</th>
					<th>CVV</th>
					<th>Amount</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var payment in Model.OrderBy(n => n.Amount))
				{
					<tr class="text-center">
						<td>@Html.DisplayFor(model => payment.CardNumber)</td>
						<td>@Html.DisplayFor(model => payment.ExpirationDate)</td>
						<td>@Html.DisplayFor(model => payment.CVV)</td>
						<td>@Html.DisplayFor(model => payment.Amount)</td>
						<td>
							<div class="w-100 btn-group" role="group">
								<a class="btn btn-outline-primary" asp-action="UpdatePayment" asp-route-id="@payment.Id"><i class="bi bi-pencil square"></i>Update</a>
								<a class="btn btn-outline-info" asp-action="Details" asp-route-id="@payment.Id"><i class="bi bi-eye"></i>Details</a>
								<a class="btn btn-outline-danger" asp-action="DeletePayment" asp-route-id="@payment.Id"><i class="bi bi-trash-fill"></i>Delete</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>

OnlinePizzeria/Views/CreditCardPayment/UpdatePayment.cshtml
@model CreditCardPaymentViewModel

@{
    ViewData["Title"] = "Update payment";
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2 class="text-center">Update Payment</h2>
                </div>
                <div class="card-body">
                    <form asp-action="UpdatePayment" enctype="multipart/form-data">
                        <input type="hidden" asp-for="Id" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="mb-3">
                            <label asp-for="CardNumber" class="form-label">Card Number:</label>
                            <input asp-for="CardNumber" class="form-control" pattern="^(?:(?<visa>4[0-9]{3}-?[0-9]{4}-?[0-9]{4}-?[0-9]{4}(?:-?[0-9]{3})?)|(?<mastercard>5[1-5][0-9]{14}))$" required placeholder="Enter a credit card number...">
                            <span asp-validation-for="CardNumber" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="CVV" class="form-label">CVV:</label>
                            <input asp-for="CVV" class="form-control" pattern="^[0-9]{3,4}$" required placeholder="Enter a valid CVV number...">
                            <span asp-validation-for="CVV" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="ExpirationDate" class="form-label">Expiration Date:</label>
                            <input asp-for="ExpirationDate" class="form-control" pattern="^(0[1-9]|1[0-2])\/?([0-9]{4}|[0-9]{2})$" required placeholder="Enter a valid expiration date...">
                            <span asp-validation-for="ExpirationDate" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="Amount" class="form-label">Amount:</label>
                            <input asp-for="Amount" class="form-control" required placeholder="Enter an amount...">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>

                        <div class="mb-3">
                            <label asp-for="CustomerId" class="form-label">Customer:</label>
                            <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.Customers"></select>
                        </div>

                        <div class="mb-3">
                            <label asp-for="OrderId" class="form-label">Address:</label>
                            <select asp-for="OrderId" class="form-control" asp-items="ViewBag.Orders"></select>
                        </div>

                        <div class="mb-3">
                            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <input type="submit" value="Update" class="btn btn-outline-success float-end" />
                                <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>